Admin:
  - 'code/modules/admin/**'
  - 'waspstation/code/modules/admin/**'

# Any file within the config subfolder
Config:
  - 'config/**'

Dependencies:
  - '**/package.json'
  - '**/package-lock.json'
  - '**/yarn.lock'

# When the .DME is changed
DME Edit:
  - './*.dme'
  - '**/*.dme'

# Any .dmi changes
Sprites:
  - '**/*.dmi'

# Javascript changes
Javascript:
  - '**/*.js'

# Changes to a .dmm or anything in the _map subfolder
Map Change:
  - '**/*.dmm'
  - '_maps/**'

# Non-modular changes
Non-Modular:
  - 'code/**'
  - 'icons/**'

# Any changes to .ogg files are marked as sound
Sound:
  - '**/*.ogg'

# Changes to the SQL subfolder
SQL:
  - 'SQL/**'

# Encompasses both the tgui and the tgui-next folder
tgui:
  - 'tgui/**'
  - 'tgui-next/**'

# Changes to the .Github folder
Github:
  - '.github/**'
